# view_logs.py

def view_logs():
    try:
        with open("firewall_logs.txt", "r") as file:
            logs = file.read()
            if logs.strip():
                print("📜 Firewall Logs:\n")
                print(logs)
            else:
                print("✅ No logs found. The firewall hasn't blocked any requests yet.")
    except FileNotFoundError:
        print("⚠️ Log file not found. Make sure firewall_logs.txt exists and is generated by your middleware.")

if __name__ == "__main__":
    view_logs()
